
[[main]]
  name = "ğŸ“–æ“ä½œã‚¬ã‚¤ãƒ‰"
  url = "/docs/setup/"
  weight = 10


[[main]]
  name = "ğŸ’°æ–™é‡‘"
  url = "/docs/system/price/"
  weight = 20
[[main]]
  name = "ãŠçŸ¥ã‚‰ã›"
  url = "/blog/"
  weight = 21

[[main]]
  name = "é€†å¼•ãè¾å…¸"
  identifier = "reverse-lookup/about/about"
  url = "/reverse-lookup/"
  weight = 26

[[main]]
  name = "ğŸ“©å•åˆã›"
  url = "/docs/system/inquery/"
  weight = 30

[[footer]]
  name = "Tags"
  url = "/tags/"
  weight = 20


[[sidebar_tips]]
  name = "æ´»ç”¨è¡“Tips"
  pageRef = "/tips"
  weight = 10


[[sidebar_others]]
  name = "å•ã„åˆã‚ã›ç­‰"
  pageRef = "/others"
  weight = 13
